### ndarray对象

ndarray 是一个n维数组对象，创建 ``ndarray`` 对象只需要调用 ``numpy.array()`` 即可

In [ ]:
# 创建 ndarray 对象

import numpy as np
a = np.array([1,2,3]) # <class 'numpy.ndarray'>
# a = np.array((1,2,3)) # 两者均可
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


### numpy 矩阵和数组的区别

In [ ]:
import numpy as np # 导入numpy pip install numpy
a = np.array([[1,2],[3,4]]) # 创建数组，二维数组
a_m = np.matrix([[1,2],[3,4]]) # 创建矩阵
print(type(a)) #  <class 'numpy.ndarray'>
print(type(a_m)) #  <class 'numpy.matrix'>
print(a)
print(a_m)
print(a*a) # 对应位置元素相乘
print(a_m*a_m) # 矩阵相乘


<class 'numpy.ndarray'>
<class 'numpy.matrix'>
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]
