## ndarray对象 np.array

ndarray 是一个n维数组对象，创建 ``ndarray`` 对象只需要调用 ``numpy.array()`` 即可

In [ ]:
# 创建 ndarray 对象

import numpy as np
a = np.array([1,2,3]) # <class 'numpy.ndarray'>
# a = np.array((1,2,3)) # 两者均可
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


### numpy 矩阵和数组的区别

In [1]:
import numpy as np # 导入numpy pip install numpy
a = np.array([[1,2],[3,4]]) # 创建数组，二维数组
a_m = np.matrix([[1,2],[3,4]]) # 创建矩阵
print(type(a)) #  <class 'numpy.ndarray'>
print(type(a_m)) #  <class 'numpy.matrix'>
print(a)
print(a_m)
print(a*a) # 对应位置元素相乘
print(a_m*a_m) # 矩阵相乘


<class 'numpy.ndarray'>
<class 'numpy.matrix'>
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [ ]:
import numpy as np
np.array([1,2])
"""
object ： 数组序列
dtype：可选参数、通过它可以更改数组类型
copy：可选，当数据源为ndarray时表示数组能否被复制、默认为True
order：可选、以哪种内存布局来创建数组、分别为C(行序列)、F(列序列)、A(默认)
ndmin：可选、用于指定数组的维度
subok：可选、类型为bool、默认False。当为True时，使用object内部数据类型、为False时、使用数组数据类型
"""

In [ ]:

# 创建一维数组
# object 可以是元组，也可以是列表
import numpy as np


a = np.array((1,2,3)) #  [1 2 3] 元组来生成ndarray
print(a) 
print(type(a)) # <class 'numpy.ndarray'>

b = np.array([1,2,3]) # 列表来生成
print(b) 
print(b.ndim)

[1 2 3]
<class 'numpy.ndarray'>
[[1 2 3]]
2


In [ ]:
# 创建二维数组
import numpy as np 
a = np.array([[1,2],[3,4]]) # 两个[]，二维
print(a)
a.ndim

[[1 2]
 [3 4]]


2

In [26]:
import numpy as np
a = np.array(range(10))
print(a)
np.array([1,2,3,4,5,6,7])
print(np.array((1,2,3,4,5,6,7))) # 元组

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7]


In [ ]:
# 不同类型 dtype
np.array([1,2,3,4.5]) # 默认选取所占用内存空间最大的数据类型

np.array([1.2, 2.3, 3.4, 4.5, 5.6], dtype=int) # round(1.5) 是四舍五入， 这里直接强制转换 int(1.2)

array([1, 2, 3, 4, 5])

In [ ]:
"""
object ： 数组序列
dtype：可选参数、通过它可以更改数组类型
copy：可选，当数据源为ndarray时表示数组能否被复制、默认为True
order：可选、以哪种内存布局来创建数组、分别为C(行序列)、F(列序列)、A(默认)
ndmin：可选、用于指定数组的维度
subok：可选、类型为bool、默认False。当为True时，使用object内部数据类型、为False时、使用数组数据类型
"""
a = np.array([1,2,3]) # 定义数组a
print(a)
b = np.array(a,copy=False) # 不可以被复制
c = np.array(a,copy=True) # 可以被复制
print(b)
print(c)
print(id(a)) # 3037513901136
print(id(b)) # 3037513901136
print(id(c)) # 3037513865040

[1 2 3]
[1 2 3]
[1 2 3]
3037513901424
3037513901424
3037513901136


In [36]:
a = np.array([1,2,3,4],ndmin=2)
a

array([[1, 2, 3, 4]])

## 函数创建ndarray对象

In [37]:
np.arange(10) #0-10 step:1 左闭右开 range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [ ]:
# 创建等差数列
a = np.linspace(1, 10, 10, endpoint=False, dtype=float) # start=1, end=10, num=10, endpoint=False 不包含10
print(a)

[1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]


In [ ]:
# 创建等比数列
a = np.logspace(0, 9, 10, base=2) # base=2, 2^0 - 2^9 生成10个数
print(a)

b = np.logspace(1, 2, num=10) # base默认为10，10^1 - 10^2 生成10个数
print(b)

[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]
[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [51]:
# 创建全为0的数组
a = np.zeros(3)
print(a)

b = np.zeros((2, 3)) # 二维数组 2x3
print(b)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [53]:
# 创建全为1的数组
a = np.ones(3)
print(a)

b = np.ones((3, 2)) # 二维数组 3x2
print(b)

c = np.ones((1, 2, 3)) # 三维数组
print(c)

[1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]]]


## 数组属性

In [ ]:
# 数组属性 shape
a = np.array([[1, 2], [3, 4]])
print(a)
print(a.shape) #(2, 2)

[[1 2]
 [3 4]]
(2, 2)


In [56]:
# reshape 更改形状
a = np.arange(12)
print(a)
a.reshape((2,6)) # 更改形状 对ndarray

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
# resize
a = np.arange(12)
print(a)
a.resize((2,7)) # 对ndarray进行resize，以0填充
print(a)

a = np.arange(12)
b = np.resize(a, (3,5)) # numpy的resize，以前面的数填充
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11  0  0]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11  0  1  2]]


In [62]:
# ndim 维度
# size 元素个数
a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])
print(a.ndim) 
print(b.ndim)
print(a.size)
print(b.size)

1
2
3
4


In [63]:
# dtype 元素类型
# itemsize 每个元素的大小，字节为单位
a = np.array([1,2,3,4])
print(a)
print(a.dtype)
print(a.itemsize)

[1 2 3 4]
int32
4


In [ ]:
# 字节 8bit=1字节 float64 8字节
a = np.array([1.0, 2, 3, 4])
print(a)
print(a.dtype) # float64
a.itemsize

[1. 2. 3. 4.]
float64


8

## 索引与切片

In [65]:
# 索引和切片
a = np.array(range(10))
print(a)
print(a[1]) # 1
print(a[1:5]) # 左闭右开
print(a[:]) # [0 1 2 3 4 5 6 7 8 9]
print(a[1:-1:2]) # [1 3 5 7]
print(a[::-1]) # 数组的倒置

[0 1 2 3 4 5 6 7 8 9]
1
[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]
[9 8 7 6 5 4 3 2 1 0]


In [66]:
# 二维数组的索引与切片

a = np.arange(16).reshape(4,4)
print(a)
print(a[1]) # 第二行 [4 5 6 7]
print(a[2][2]) # 10
print(a[2:]) # 第三行之后元素

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[4 5 6 7]
10
[[ 8  9 10 11]
 [12 13 14 15]]


In [67]:
a = np.arange(16).reshape(4,4)
print(a) 
print(a[...,1]) # 在行位置使用...,则代表选取所有行元素 [ 1  5  9 13]
print(a[1,...]) # 在列位置使用...,则代表选取所有列元素 [ 1  5  9 13]
print(a[...,1:]) # 行全选，从第二列到最后一列

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 1  5  9 13]
[4 5 6 7]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [68]:
a = np.arange(16).reshape(4,4)
print(a) 
a[...][1] # a[...]=a

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([4, 5, 6, 7])

In [69]:
a = np.arange(16).reshape(4,4)
print(a) 
b = a[[0,1],[0,1]] # 第0行第0列，第1行第1列
b # array([0, 5])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([0, 5])

In [70]:
# 布尔索引
a = np.arange(10)
a[a > 5] # 取 为True 的值

array([6, 7, 8, 9])

## 广播

In [74]:
# 广播
a = np.arange(12).reshape(3,4)
print(a.shape)
print(a)

b = np.array([1,2,3,4])
print(b.shape)
print(b)
c = a+b
c

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(4,)
[1 2 3 4]


array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11],
       [ 9, 11, 13, 15]])

## 函数

In [ ]:
# 求平均值
a = np.arange(12).reshape(3,4)
print(a)
a.mean(axis=0) #  沿着第0轴（行）进行操作，跨行、即垂直方向；求每一列的平均值

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([4., 5., 6., 7.])

In [77]:
# 求最大值
a = np.arange(12).reshape(3,4)
print(a)
a.max(axis=1) #  沿着第1轴（列）进行操作，跨列、即水平方向；求每一行的最大值

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 3,  7, 11])

In [78]:
# 求中位数
b = np.array([1,2,3,4,5]) # 求中位数
np.median(b)

3.0

In [79]:
# 标准差
b = np.array([1,2,3,4,5])  # 标准差
np.std(b)

1.4142135623730951

In [86]:
# 随机数
np.random.rand(4,2) # 0-1

array([[0.48148928, 0.17031767],
       [0.17548203, 0.61059468],
       [0.19420621, 0.11290982],
       [0.20412132, 0.00651851]])

In [91]:
np.random.randn(4,2) # 具有标准正态分布的随机数 均值为0、标准差为1

array([[ 0.19593521, -0.0379231 ],
       [-0.27914579, -1.34556868],
       [ 0.09272275, -0.93354768],
       [ 0.40898172, -0.81190519]])

In [ ]:
np.random.randint(-10,10,size=(2,2)) # [-10,10) 2x2

array([[-5,  3],
       [-6, -5]])

In [138]:
# 随机数种子
np.random.seed(22) # 指定为一个特定的数，在这个数下面随机的都一致
np.random.randn(4,2)  # 具有标准正态分布的随机数

array([[-0.09194992, -1.46335065],
       [ 1.08179168, -0.23932517],
       [-0.49112914, -1.00227201],
       [ 0.9188215 , -1.1036321 ]])

In [139]:
# 添加
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(np.append(a,[7,8,9])) # 添加在最后并展平为一维

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
# 添加
a = np.array([[1,2,3],[4,5,6]])
print(np.append(a,[[7,8,9], [10,11,12]],axis=0)) # axis=0 添加行
# 注意： [[7,8,9]] 这里是二维的，若是[7,8,9]一维的会报错

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(np.append(a,[[7,8,9],[6,6,6]],axis=1))  # axis=1 添加列

[[1 2 3 7 8 9]
 [4 5 6 6 6 6]]


In [ ]:
# 插入
a = np.array([1,2,3,4])
print(a)
np.insert(a,3,5) # 插在索引"之前" 3为索引 5为要插入的值

[1 2 3 4]


array([1, 2, 5, 3, 4])

In [146]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(np.insert(a,1,[6,7,8],axis=0)) # 行前进行插入
print(np.insert(a,1,6,axis=1)) # 列前进行插入

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [6 7 8]
 [4 5 6]]
[[1 6 2 3]
 [4 6 5 6]]


In [148]:
# 删除
a = np.arange(12).reshape(3,4)
print(a)
print(np.delete(a,1,axis=0)) # 行 删除第二行
print(np.delete(a,1,axis=1)) # 列 删除第二列

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [149]:
# 去重
a = np.array([1,2,3,4,4,4,5,6,7,7])
print(a)
uq = np.unique(a) # 保留唯一值
print(uq)

[1 2 3 4 4 4 5 6 7 7]
[1 2 3 4 5 6 7]


In [ ]:
# 排序
a = np.array([[3,5,7],[4,1,10]])
print(a)
b = np.sort(a,axis=1) # 默认axis=1 沿着列进行操作，跨列，即水平方向，每一行各元素排序
b

[[ 3  5  7]
 [ 4  1 10]]


array([[ 3,  5,  7],
       [ 1,  4, 10]])