## 定义张量

In [2]:
# 张量的创建
import torch
a = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(type(a))#<class 'torch.Tensor'>
print(a.shape)
a

<class 'torch.Tensor'>
torch.Size([2, 3])


tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
a = torch.eye(2) # 对角阵
a

tensor([[1., 0.],
        [0., 1.]])

In [4]:
b = torch.zeros(3,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
c = torch.ones(3,3)
c

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
d = torch.arange(1,10,1) # start end step 左闭右开
d

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
e = torch.linspace(1,10,10) # 使用等差函数创建张量
e

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# 等比数列
f = torch.logspace(1,10,10) # 基数为10 10^1-10^10
f

tensor([1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05, 1.0000e+06,
        1.0000e+07, 1.0000e+08, 1.0000e+09, 1.0000e+10])

In [11]:
g = torch.logspace(1,2,10) # 10^1-10^2  num=10
g

tensor([ 10.0000,  12.9155,  16.6810,  21.5443,  27.8256,  35.9381,  46.4159,
         59.9484,  77.4264, 100.0000])

### 随机数生成张量

In [12]:
a1 = torch.rand(3, 3) # 随机创建张量
a1

tensor([[0.5943, 0.4316, 0.1254],
        [0.3302, 0.8512, 0.5284],
        [0.3790, 0.6280, 0.0151]])

In [24]:
a2 = torch.randn(3,3) # 符合正态分布的张量、均值为0，标准差为1
a2

tensor([[-0.6054,  1.3934,  0.1832],
        [-0.4490, -0.4233, -0.6323],
        [ 1.1156, -1.0226,  0.0068]])

In [18]:
a3 = torch.randint(1,10,(5,5))
a3

tensor([[9, 9, 6, 5, 1],
        [7, 4, 5, 2, 1],
        [1, 6, 4, 1, 7],
        [4, 6, 7, 7, 7],
        [7, 5, 9, 7, 3]])

### Numpy数组转化为Pytorch张量

In [26]:
import numpy as np

a4 = np.array([1, 2])
print(type(a4))
print(a4)

<class 'numpy.ndarray'>
[1 2]


In [27]:
a5 = torch.from_numpy(a4)
print(type(a5))
print(a5)

<class 'torch.Tensor'>
tensor([1, 2], dtype=torch.int32)


## 张量的索引

In [33]:
import torch
a = torch.Tensor(2,3,128,128) # 2张图片，每张图片3通道(RGB)，高宽为128x128
print(a.shape)
print(a[0].shape) # 取第一张图像 torch.Size([3, 128, 128])
print(a[0][0].shape) # 取第一张图像的第一通道 torch.Size([128, 128])
print(a[0][0][0].shape) # torch.Size([128])

a1 = torch.rand(64, 10) # 随机创建张量
print(a1.shape)
print(a1[63].shape)

torch.Size([2, 3, 128, 128])
torch.Size([3, 128, 128])
torch.Size([128, 128])
torch.Size([128])
torch.Size([64, 10])
torch.Size([10])


## 张量的切片

In [ ]:
#tensor[start:end:step]

import torch
a = torch.Tensor(2,3,128,128) # 2张图片，每张图片3通道(RGB)，高宽为128x128
print(a.shape)
print(a[:,:,:,:].shape)
print(a[:1,:,:,:].shape) # 取第一张图
print(a[:1,:1,:,:].shape) # 取第一张图的第一个通道
print(a[:1,:1,:64,:64].shape) # torch.Size([1, 1, 64, 64]) 取第一张图的第一个通道的左上四分之一
print(a[:1,:1,:64:2,:64:2].shape) # torch.Size([1, 1, 32, 32]) 在上面基础上跳着一个像素点取

torch.Size([2, 3, 128, 128])
torch.Size([2, 3, 128, 128])
torch.Size([1, 3, 128, 128])
torch.Size([1, 1, 128, 128])
torch.Size([1, 1, 64, 64])
torch.Size([1, 1, 32, 32])


In [ ]:
a = torch.randn(2,3,128,128)
print(a[:1,:1,:1,:1])  # 取第一张图的第一个通道 第一个像素点 像素值

tensor([[[[-0.6759]]]])


## 维度变换

In [ ]:
# 使用reshape改变张量
a = torch.randn(2,3,128,128) # 使用reshape改变张量
b = a.reshape(2,3,-1) # 4维->3维    16384=128x128
print(b.shape)
c = a.reshape(4,-1) # 4维->2维
print(c.shape) # 24576=(2*3*128*128)/4

torch.Size([2, 3, 16384])
torch.Size([4, 24576])


In [ ]:
# 维度的增加
a = torch.randn(2,3,128,128) # 维度的增加
a = a.unsqueeze(2) # a.unsqueeze(0).shape  维度添到维度2的前面（维度0,1,2...）
a.shape

torch.Size([2, 3, 1, 128, 128])

In [40]:
a = torch.randn(2,3,128,128) # 维度的删减 只能删除大小为一的维度
a = a.squeeze(1)
print(a.shape)

b = torch.randn(2,1,128,128) # 维度的删减 只能删除大小为一的维度
b = b.squeeze(1)
print(b.shape)

torch.Size([2, 3, 128, 128])
torch.Size([2, 128, 128])


## 维度调整

In [42]:
a = torch.randn(2,3,128,128) # 交换维度，且只能交换张量中某两个维度的顺序
print(a.shape)
a = a.transpose(0,2)
print(a.shape)

torch.Size([2, 3, 128, 128])
torch.Size([128, 3, 2, 128])


In [43]:
a = torch.randn(2,3,128,64) # torch.Size([3, 2, 64, 128]) 多个维度的交换
print(a.shape)
a = a.permute(1,0,3,2)
print(a.shape)

torch.Size([2, 3, 128, 64])
torch.Size([3, 2, 64, 128])


In [44]:
a = torch.randn(2,1,128,64) # 将一个维度大小为1的维度扩展为其他大小
print(a.shape)
a = a.expand(2,3,128,64)
print(a.shape)

torch.Size([2, 1, 128, 64])
torch.Size([2, 3, 128, 64])
